python ./scripts/fill_db.py -f data/db_entries0.pkl
python ./scripts/fill_db.py -f data/db_entries1.pkl
python ./scripts/fill_db.py -f data/db_entries2.pkl
python ./scripts/fill_db.py -f data/db_entries3.pkl
python ./scripts/fill_db.py -f data/db_entries4.pkl
python ./scripts/fill_db.py -f data/db_entries5.pkl
python ./scripts/fill_db.py -f data/db_entries6.pkl
python ./scripts/fill_db.py -f data/db_entries7.pkl
python ./scripts/fill_db.py -f data/db_entries8.pkl
python ./scripts/fill_db.py -f data/db_entries9.pkl
python ./scripts/fill_db.py -f data/db_entries10.pkl
python ./scripts/fill_db.py -f data/db_entries11.pkl
python ./scripts/fill_db.py -f data/db_entries12.pkl
python ./scripts/fill_db.py -f data/db_entries13.pkl
python ./scripts/fill_db.py -f data/db_entries14.pkl
python ./scripts/fill_db.py -f data/db_entries15.pkl
python ./scripts/fill_db.py -f data/db_entries16.pkl
python ./scripts/fill_db.py -f data/db_entries17.pkl
python ./scripts/fill_db.py -f data/db_entries18.pkl
python ./scripts/fill_db.py -f data/db_entries19.pkl
python ./scripts/fill_db.py -f data/db_entries20.pkl
python ./scripts/fill_db.py -f data/db_entries21.pkl
python ./scripts/fill_db.py -f data/db_entries22.pkl
python ./scripts/fill_db.py -f data/db_entries23.pkl
python ./scripts/fill_db.py -f data/db_entries24.pkl
python ./scripts/fill_db.py -f data/db_entries25.pkl
python ./scripts/fill_db.py -f data/db_entries26.pkl
python ./scripts/fill_db.py -f data/db_entries27.pkl
python ./scripts/fill_db.py -f data/db_entries28.pkl
python ./scripts/fill_db.py -f data/db_entries29.pkl
python ./scripts/fill_db.py -f data/db_entries30.pkl
python ./scripts/fill_db.py -f data/db_entries31.pkl
python ./scripts/fill_db.py -f data/db_entries32.pkl
python ./scripts/fill_db.py -f data/db_entries33.pkl
python ./scripts/fill_db.py -f data/db_entries34.pkl
python ./scripts/fill_db.py -f data/db_entries35.pkl
python ./scripts/fill_db.py -f data/db_entries36.pkl
python ./scripts/fill_db.py -f data/db_entries37.pkl
python ./scripts/fill_db.py -f data/db_entries38.pkl
python ./scripts/fill_db.py -f data/db_entries39.pkl
python ./scripts/fill_db.py --collection_name cord19scibertoverview -f data/overview0.pkl
